### ISSUE TITLE
As an user I should be able to see all current rooms when I log into vibey

### ISSUE THREAD

**Issue by hrishikeshpaul** [hrishikeshpaul/vibey#62]
### Info

When the user logs into the the vibey homepage, they should be able to get a list of the all the current that are playing songs.

### Proposed method

For now, we can keep it simple, and keep a refresh button on the navbar (beside the create button) and get rooms via an API call.

#### Backend 
1.  `/rooms` - API to get the get the current rooms (which are in Redis) and then run it through mongo to get the room data (name, desc, tags etc).
2. Since redis is going to be keeping track of the current track and the users in the room, that will also be returned.
3. Keep a limit to 15 rooms, and make the API take an offset to paginate it.

### Frontend
1. Display the rooms using the room card
2. The user can click on refresh, which will take the user to the top of the page and the full list will be refreshed.
3. As the user reaches the bottom of the div, make the api call with the appropriate offset to get the next set of rooms

**Comment by hrishikeshpaul** [comment]
@s-munro thoughts?

**Comment by s-munro** [comment]
Sounds good to me as well.  Let's decide what the shape of the data should be; we won't need everything if we're just displaying the cards to users on the FE.  Although, since it's just the GET `/rooms` call, it would also make sense to send back all of the data... what do you think?  According to the mockups, I fleshed out all of the data we would need, in theory

<img width="796" alt="Screen Shot 2021-08-12 at 7 32 12 PM" src="https://user-images.githubusercontent.com/68410363/129282844-025849ee-0bb8-4e69-bab3-c13ee54e536a.png">

With the mockup in mind, we'll need it like this:
```
room = {
  name: string;
  host: string; (we only are displaying the username)
  tags: Tag[];
  currentUsers: number;
  song: {
    img: string;
    name: string;
    artist: string;
  };
};
```
Sound good to you?  We're also displaying the # of likes in the mockups, but that's not a part of our schema right now

**Comment by hrishikeshpaul** [comment]
Let's just send back the whole host object for now. It'll just be easier on our end

**Comment by hrishikeshpaul** [comment]
Also I changed up the cars a little bit from the pickups cause I believed it would be better. It's how it is on the FE rn
